Repository OpenCubicChunks/CubicChunks, pull requests merged in 2021-06, with the labels that each got.

#699 First attempt to update for 21w20a
  gradle.properties
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/CubicAquifer.java
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/heightmap/SurfaceTrackerWrapper.java
  src/main/java/io/github/opencubicchunks/cubicchunks/debug/DebugVisualization.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/MixinChunkManager.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/MixinChunkStatus.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/MixinISelectiveWorker.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/MixinWorldGenRegion.java
  src/main/java/io/github/opencubicchunks/cubicchunks/world/CubeWorldGenRegion.java
  src/main/java/io/github/opencubicchunks/cubicchunks/world/DummyHeightmap.java
  src/main/java/io/github/opencubicchunks/cubicchunks/world/storage/RegionCubeIO.java
Labels: 1.17, Compatibility

#708 implement minor optimisation for server ticklist, to be replaced shortly
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/MixinServerTickList.java
Labels: 1.17, Performance

#710 Optimize caves & carvers by only using the size of the current cube not the size of NoiseAndSurfaceBuilderHelper.
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/CubicAquifer.java
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/NoiseAndSurfaceBuilderHelper.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/MixinChunkStatus.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/MixinNoiseBasedChunkGenerator.java
Labels: 1.17, Performance

#712 Correctly chain future dependencies in noise status
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/cube/CubePrimer.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/MixinChunkStatus.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/server/MixinServerWorldLightManager.java
Labels: 1.17, Bug

#722 -Don't read columns in section storage when updating. Read cubes instead.
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/storage/ISectionStorage.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/MixinChunkManager.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/storage/MixinSectionStorage.java
Labels: Bug

#721 Fix broken features & Fix vertical features by saving the blocks that would of otherwise been cut off to cubes not past liquid carvers status
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/IBigCube.java
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/cube/CubePrimer.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/MixinChunkStatus.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/biome/MixinBiome.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/feature/MixinDesertWellFeature.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/feature/MixinFossilFeature.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/feature/MixinIcePatchFeature.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/feature/MixinIceSpikeFeature.java
  src/main/java/io/github/opencubicchunks/cubicchunks/world/CubeWorldGenRegion.java
  src/main/java/io/github/opencubicchunks/cubicchunks/world/storage/CubeSerializer.java
  src/main/resources/cubicchunks.mixins.core.json
Labels: 1.17, Compatibility
