Repository OpenCubicChunks/CubicChunks, pull requests merged in 2021-04, with the labels that each got.

#651 Reimplement Entity Tracker + Saving
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/ClientChunkProviderCubeArray.java
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/ImposterChunkPos.java
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/cube/CubePrimer.java
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/storage/CubicEntityStorage.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/access/common/ChunkManagerAccess.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/client/entity/MixinTransientEntitySectionManager.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/client/world/MixinClientChunkProvider.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/client/world/MixinClientWorld.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/MixinChunkHolder.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/storage/MixinEntityStorage.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/entity/MixinPersistentEntitySectionManager.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/entity/storage/MixinEntitySectionStorage.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/MixinServerWorld.java
  src/main/java/io/github/opencubicchunks/cubicchunks/world/client/IClientWorld.java
  src/main/java/io/github/opencubicchunks/cubicchunks/world/entity/IsCubicEntityContext.java
  src/main/resources/cubicchunks.mixins.core.json
Labels: 1.17, High priority, Vanilla feature: reimplement

#653 Update to 21w13a
  gradle.properties
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/cube/BigCube.java
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/cube/CubePrimer.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/client/debug/MixinChunkBorderRenderer.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/cave/legacy/MixinWorldCarver.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/placement/MixinAbstractBiasedRangedDecorator.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/placement/MixinAbstractRangeDecorator.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/placement/MixinBiasedToBottomHeight.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/placement/MixinUniformHeight.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/structure/MixinStructureStart.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/structure/pieces/MixinOceanRuinPieces.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/optifine/client/vanilla/MixinWorldRenderer_Vanilla.java
  src/main/java/io/github/opencubicchunks/cubicchunks/world/CubeWorldGenRegion.java
  src/main/resources/cubicchunks.mixins.core.json
Labels: 1.17

#654 Update to 21w14a & FIx & Update Aquifer's Mixin
  gradle.properties
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/cube/CubePrimer.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/access/common/NoiseGeneratorSettingsAccess.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/MixinNoiseBasedChunkGenerator.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/cave/MixinAquifer.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/biome/MixinBiome.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/feature/MixinBlockBlobFeature.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/surfacebuilder/MixinBadlandsSurfaceBuilder.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/surfacebuilder/MixinDefaultSurfaceBuilder.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/surfacebuilder/MixinErodedBadlandsSurfaceBuilder.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/surfacebuilder/MixinFrozenOceanSurfaceBuilder.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/surfacebuilder/MixinSwampSurfaceBuilder.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/surfacebuilder/MixinWoodedBadlandsSurfaceBuilder.java
  src/main/resources/cubicchunks.mixins.core.json
Labels: 1.17

#656 Fix missing portion of save format and fix cube primer wrapper
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/cube/CubePrimerWrapper.java
  src/main/java/io/github/opencubicchunks/cubicchunks/world/storage/CubeSerializer.java
Labels: 1.17

#657 [1.17] Finish Cube Serialization (does NOT include heightmap, Upgrade Data, or light engine saving)
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/IBigCube.java
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/ImposterChunkPos.java
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/cube/BigCube.java
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/cube/CubePrimer.java
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/storage/POIDeserializationContext.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/access/common/ChunkSerializerAccess.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/MixinChunkManager.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/storage/MixinPoiManager.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/structure/MixinStructureFeature.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/structure/MixinStructureStart.java
  src/main/java/io/github/opencubicchunks/cubicchunks/world/storage/CubeSerializer.java
  src/main/resources/cubicchunks.mixins.access.json
Labels: 1.17, Vanilla feature: reimplement

#673 [1.17] Introduce CubePlayerProvider for player tracking
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/CubePlayerProvider.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/MixinChunkHolder.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/MixinChunkManager.java
Labels: 1.17

#672 [1.17] Make PacketCubeBlockChanges Section Based
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/MixinChunkHolder.java
  src/main/java/io/github/opencubicchunks/cubicchunks/network/PacketCubeBlockChanges.java
  src/main/java/io/github/opencubicchunks/cubicchunks/utils/Coords.java
Labels: 1.17

#671 [1.17] Columns before cubes load order
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/IChunkManager.java
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/ICubeHolder.java
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/ticket/ITicketManager.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/DebugMixinConfig.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/access/common/ChunkManagerAccess.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/MixinServerChunkProvider.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/MixinChunkHolder.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/MixinChunkManager.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/MixinProtoChunk.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/ticket/MixinTicketManager.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/debug/common/MixinMinecraftServer.java
  src/main/java/io/github/opencubicchunks/cubicchunks/server/IServerChunkProvider.java
Labels: 1.17

#668 Add another status renderer option for debugging
  build.gradle
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/DebugMixinConfig.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/client/debug/MixinGameRenderer.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/debug/client/MixinLevelRenderer.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/debug/common/MixinDistanceManager.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/debug/common/MixinMinecraftServer.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/debug/common/MixinPlayerRespawnLogic.java
  src/main/resources/cubicchunks.mixins.debug.json
Labels: 1.17

#678 [1.17] Stop overwriting existing chunk sections
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/NoiseAndSurfaceBuilderHelper.java
Labels: 1.17

#682 [1.17] Seperate Server & Client
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/ChunkCubeGetter.java
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/biome/ColumnBiomeContainer.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/client/chunk/MixinChunk.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/MixinChunk.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/MixinChunkManager.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/network/MixinClientboundLevelChunkPacket.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/server/MixinPlayerList.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/MixinWorld.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/server/chunk/MixinChunk.java
  src/main/java/io/github/opencubicchunks/cubicchunks/network/PacketCCLevelInfo.java
  src/main/java/io/github/opencubicchunks/cubicchunks/network/PacketDispatcher.java
  src/main/java/io/github/opencubicchunks/cubicchunks/server/CubicLevelHeightAccessor.java
  src/main/resources/cubicchunks.mixins.core.json
Labels: 1.17, High priority

#669 [1.17] Fix Block Entities(i.e Chests)
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/cube/BigCube.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/MixinChunk.java
  src/main/java/io/github/opencubicchunks/cubicchunks/world/CubeWorldGenRegion.java
  src/main/java/io/github/opencubicchunks/cubicchunks/world/storage/CubeSerializer.java
Labels: 1.17

#679 [1.17] New Colours for loading screen
  src/main/java/io/github/opencubicchunks/cubicchunks/client/CubicWorldLoadScreen.java
Labels: 1.17

#683 [1.17] Cube Async Entity Loading & Stop Saving Empty Tags
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/storage/MixinEntityStorage.java
  src/main/java/io/github/opencubicchunks/cubicchunks/world/storage/CubeSerializer.java
  src/main/java/io/github/opencubicchunks/cubicchunks/world/storage/RegionCubeIO.java
Labels: 1.17, Bug

#684 [1.17] Make blockpos over the network suitable for Cubic Chunks
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/network/MixinFriendlyByteBuf.java
  src/main/resources/cubicchunks.mixins.core.json
Labels: 1.17, Blocker/Critical, Compatibility

#685 [1.17] Update to 21w17a
  gradle.properties
Labels: 1.17
