Repository OpenCubicChunks/CubicChunks, pull requests merged in 2021-02, with the labels that each got.

#625 [1.17] Add Vertical Render Distance
  src/main/java/io/github/opencubicchunks/cubicchunks/CubicChunks.java
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/ClientChunkProviderCubeArray.java
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/IChunkManager.java
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/IClientCubeProvider.java
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/IVerticalView.java
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/graph/CubeDistanceGraph.java
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/ticket/HorizontalGraphGroup.java
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/ticket/ITicketManager.java
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/ticket/PlayerCubeTicketTracker.java
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/ticket/VerticalGraphGroup.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/access/client/OptionAccess.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/access/common/TicketManagerAccess.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/client/MixinGameRenderer.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/client/MixinOptions.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/client/MixinVideoSettingsScreen.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/client/MixinViewFrustum.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/client/server/MixinIntegratedPlayerList.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/client/server/MixinIntegratedServer.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/client/world/MixinClientChunkProvider.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/MixinServerChunkProvider.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/MixinChunkHolder.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/MixinChunkManager.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/server/MixinPlayerList.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/ticket/MixinTicketManager.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/optifine/client/vanilla/MixinWorldRenderer_Vanilla.java
  src/main/java/io/github/opencubicchunks/cubicchunks/network/PacketCubeCacheRadius.java
  src/main/java/io/github/opencubicchunks/cubicchunks/network/PacketDispatcher.java
  src/main/resources/assets/cubicchunks/lang/en_us.json
  src/main/resources/cubicchunks.mixins.access.json
  src/main/resources/cubicchunks.mixins.core.json
  src/main/resources/pack.mcmeta
Labels: 1.17

#628 [1.17] World Tick Spawner
  buildSrc/src/main/java/io/github/opencubicchunks/gradle/MixinGenExtension.java
  config/checkstyle/suppressions.xml
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/biome/CubeBiomeContainer.java
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/cube/BigCube.java
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/heightmap/SurfaceTrackerSection.java
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/util/CubePos.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/ASMConfigPlugin.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/CCMixinConnector.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/access/common/NaturalSpawnerAccess.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/access/common/SpawnStateAccess.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/asm/common/MixinAsmTarget.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/MixinServerChunkProvider.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/MixinProtoChunk.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/ticket/MixinTicketManager.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/MixinNaturalSpawner.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/transform/MainTransformer.java
  src/main/java/io/github/opencubicchunks/cubicchunks/server/IServerChunkProvider.java
  src/main/java/io/github/opencubicchunks/cubicchunks/world/CubicNaturalSpawner.java
  src/main/java/io/github/opencubicchunks/cubicchunks/world/INaturalSpawnerInternal.java
  src/main/resources/cubicchunks.mixins.access.json
Labels: 1.17

#631 -Cubify all vanilla surface builders to prevent exceptions
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/surfacebuilder/MixinBadlandsSurfaceBuilder.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/surfacebuilder/MixinDefaultSurfaceBuilder.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/surfacebuilder/MixinErodedBadlandsSurfaceBuilder.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/surfacebuilder/MixinFrozenOceanSurfaceBuilder.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/surfacebuilder/MixinSwampSurfaceBuilder.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/surfacebuilder/WoodedBadlandsSurfaceBuilder.java
  src/main/resources/cubicchunks.mixins.core.json
Labels: 1.17

#635 [1.17] Rewrite CubeBiomeContainer to be comprised of several Vanilla Biome Containers
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/IBigCube.java
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/IClientCubeProvider.java
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/biome/ColumnBiomeContainer.java
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/biome/CubeBiomeContainer.java
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/cube/BigCube.java
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/cube/CubePrimer.java
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/cube/CubePrimerWrapper.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/access/common/BiomeContainerAccess.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/client/world/MixinClientChunkProvider.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/MixinChunkGenerator.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/MixinChunkStatus.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/MixinNaturalSpawner.java
  src/main/java/io/github/opencubicchunks/cubicchunks/network/PacketCubes.java
  src/main/java/io/github/opencubicchunks/cubicchunks/network/PacketDispatcher.java
  src/main/java/io/github/opencubicchunks/cubicchunks/world/CubicNaturalSpawner.java
  src/main/java/io/github/opencubicchunks/cubicchunks/world/storage/CubeSerializer.java
Labels: 1.17, Enhancement

#637 Optimize World Generation(Around 15 second increase when first loading a world)
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/NoiseAndSurfaceBuilderHelper.java
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/cube/CubePrimer.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/MixinServerChunkProvider.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/MixinChunkStatus.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/MixinDepthBasedReplacingBaseStoneSource.java
  src/main/resources/cubicchunks.mixins.core.json
Labels: 1.17, Performance

#638 Optimizations to aquifers, noise sampling, and random number generation
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/AquiferRandom.java
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/NoiseAndSurfaceBuilderHelper.java
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/NonAtomicWorldgenRandom.java
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/cube/CubePrimer.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/MixinBlendedNoise.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/MixinChunkGenerator.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/MixinDepthBasedReplacingBaseStoneSource.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/MixinNoiseBasedChunkGenerator.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/cave/MixinAquifer.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/cave/legacy/MixinCaveWorldCarver.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/cave/legacy/MixinWorldCarver.java
  src/main/java/io/github/opencubicchunks/cubicchunks/world/CubeWorldGenRandom.java
  src/main/resources/cubicchunks.mixins.core.json
Labels: 1.17, Performance
