Repository OpenCubicChunks/CubicChunks, pull requests merged in 2021-09, with the labels that each got.

#733 Fast tick lists implementation
  build.gradle
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/util/CubePos.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/access/common/ChunkManagerAccess.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/access/common/ServerTickListAccess.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/MixinChunkHolder.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/entity/MixinPersistentEntitySectionManager.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/MixinServerTickList.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/MixinServerWorld.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/lighting/MixinSkyLightSectionStorage.java
  src/main/java/io/github/opencubicchunks/cubicchunks/world/CubicFastServerTickList.java
  src/main/java/io/github/opencubicchunks/cubicchunks/world/CubicServerTickList.java
  src/main/java/io/github/opencubicchunks/cubicchunks/world/entity/ChunkEntityStateEventHandler.java
  src/main/java/io/github/opencubicchunks/cubicchunks/world/entity/ChunkEntityStateEventSource.java
  src/main/java/io/github/opencubicchunks/cubicchunks/world/storage/CubeSerializer.java
  src/main/resources/cubicchunks.mixins.access.json
Labels: Performance, 1.17

#696 Fix Cubic Nether Generation
  src/main/java/io/github/opencubicchunks/cubicchunks/CubicChunks.java
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/aquifer/AquiferRandom.java
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/aquifer/AquiferSample.java
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/aquifer/AquiferSourceSampler.java
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/aquifer/CubicAquifer.java
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/util/CubePos.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/access/common/BiomeGenerationSettingsAccess.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/access/common/BiomeManagerAccess.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/access/common/PoiSectionAccess.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/MixinMinecraftServer.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/MixinChunkGenerator.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/MixinNoiseBasedChunkGenerator.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/storage/MixinPoiManager.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/MixinNaturalSpawner.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/MixinPortalForcer.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/biome/MixinMultiNoiseBiomeSource.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/feature/nether/MixinBasaltPillarFeature.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/feature/nether/MixinHugeFungusFeature.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/feature/nether/MixinReplaceBlobsFeature.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/feature/nether/MixinTwistyVinesFeature.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/placement/MixinCountMultiLayerDecorator.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/structure/MixinStructurePiece.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/surfacebuilder/MixinNetherCappedSurfaceBuilder.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/surfacebuilder/MixinNetherForestSurfaceBuilder.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/surfacebuilder/MixinNetherSurfaceBuilder.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/debug/common/MixinMinecraftServer.java
  src/main/java/io/github/opencubicchunks/cubicchunks/world/gen/feature/CCFeature.java
  src/main/java/io/github/opencubicchunks/cubicchunks/world/gen/feature/CCFeatures.java
  src/main/java/io/github/opencubicchunks/cubicchunks/world/gen/feature/LavaLeakFix.java
  src/main/resources/cubicchunks.mixins.access.json
  src/main/resources/cubicchunks.mixins.core.json
Labels: Vanilla feature: reimplement, 1.17

#674 implement a fast hashset for 3D integer points
  src/main/java/io/github/opencubicchunks/cubicchunks/utils/Int3HashSet.java
  src/test/java/io/github/opencubicchunks/cubicchunks/utils/Int3HashSetTest.java
Labels: High priority, Code quality, 1.17
