Repository OpenCubicChunks/CubicChunks, pull requests merged in 2021-05, with the labels that each got.

#687 Allow teleporting past Y= +/- 20 million
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/MixinWorld.java
Labels: 1.17, Low priority

#688 Async chunk IO & serialization
  .gitignore
  buildSrc/src/main/java/io/github/opencubicchunks/gradle/MergedMappingsDependency.java
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/storage/AsyncSaveData.java
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/storage/ISectionStorage.java
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/util/CCForkJoinWorkerThreadFactory.java
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/util/ChunkIoMainThreadTaskUtils.java
  src/main/java/io/github/opencubicchunks/cubicchunks/chunk/util/ExecutorUtils.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/access/common/IOWorkerAccess.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/MixinChunkManager.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/storage/MixinEntityStorage.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/storage/MixinSectionStorage.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/storage/MixinStructureManager.java
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/storage/MixinStructureTemplatePalette.java
  src/main/java/io/github/opencubicchunks/cubicchunks/world/storage/CubeSerializer.java
  src/main/java/io/github/opencubicchunks/cubicchunks/world/storage/RegionCubeIO.java
  src/main/resources/cubicchunks.accesswidener
  src/main/resources/cubicchunks.mixins.access.json
  src/main/resources/cubicchunks.mixins.core.json
Labels: 1.17, Enhancement, Performance

#690 Update to Snapshot 21w18a
  gradle.properties
Labels: 1.17

#692 Fix Natural Spawner requesting biomes out of bound
  src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/MixinServerChunkProvider.java
Labels: 1.17, Bug
